// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmp0GziZ0GcwGUtc51uaM_G6RmXNshLFw',
    appId: '1:336862944503:web:fe6b7dbdfe2963506507f2',
    messagingSenderId: '336862944503',
    projectId: 'safebite-5c0a0',
    authDomain: 'safebite-5c0a0.firebaseapp.com',
    storageBucket: 'safebite-5c0a0.firebasestorage.app',
    measurementId: 'G-6DPT2N40VB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzjKZcr9ohCHxwlQIylNhiC4R9LbMXDhU',
    appId: '1:336862944503:android:883cce96773719706507f2',
    messagingSenderId: '336862944503',
    projectId: 'safebite-5c0a0',
    storageBucket: 'safebite-5c0a0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvscIzZcQUb4fIX_x8baaSg_svS6rB_5s',
    appId: '1:336862944503:ios:cbd31f75f147099f6507f2',
    messagingSenderId: '336862944503',
    projectId: 'safebite-5c0a0',
    storageBucket: 'safebite-5c0a0.firebasestorage.app',
    iosClientId: '336862944503-mm5udlnsk9dpdj34nmuvrm5i57kk84i7.apps.googleusercontent.com',
    iosBundleId: 'com.example.safeBite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvscIzZcQUb4fIX_x8baaSg_svS6rB_5s',
    appId: '1:336862944503:ios:cbd31f75f147099f6507f2',
    messagingSenderId: '336862944503',
    projectId: 'safebite-5c0a0',
    storageBucket: 'safebite-5c0a0.firebasestorage.app',
    iosClientId: '336862944503-mm5udlnsk9dpdj34nmuvrm5i57kk84i7.apps.googleusercontent.com',
    iosBundleId: 'com.example.safeBite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmp0GziZ0GcwGUtc51uaM_G6RmXNshLFw',
    appId: '1:336862944503:web:a8b1611fa6e769b66507f2',
    messagingSenderId: '336862944503',
    projectId: 'safebite-5c0a0',
    authDomain: 'safebite-5c0a0.firebaseapp.com',
    storageBucket: 'safebite-5c0a0.firebasestorage.app',
    measurementId: 'G-LYF832S3L8',
  );

}